#!/bin/bash
set -eo pipefail

medaka_version=$(medaka --version)
modeldata=()
while read -r line; do
    modeldata+=("$line")
done < <(medaka tools list_models)
# 0: Available models
# 1: default consensus model
# 2: default SNP model
# 3: default variant model

function follow_link {
  python -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' $1
}

declare -r HAP1OPTS="--tag_name HP --tag_value 1 --tag_keep_missing"
declare -r HAP2OPTS="--tag_name HP --tag_value 2 --tag_keep_missing"
declare -r WHATSHAPOPTS="--ignore-read-groups"

# Variables
OUTPUT="medaka_variant"
THREADS=1
THRESHOLD=0.04 # for defining secondary calls in diploid snp calling stage used to haplotype reads
BATCH_SIZE=100
REGIONS=""
iflag=false
fflag=false
DELETE=false
SNPMODEL=${modeldata[2]##* }
MODEL=${modeldata[3]##* }


usage="
${medaka_version}
-------------

Variant calling via neural networks. The input bam should be aligned to the
reference against which to call variants. Note: that although configurable
it is unlikely that the model arguments should be changed from their defaults.

$(basename "$0") [-h] -i <fastx>

    -h  show this help text.
    -i  input bam of reads aligned to ref. Read groups are currently ignored,
        so the bam should only contain reads from a single sample.
    -f  input fasta input reference (required).
    -r  region string(s). If providing multiple regions, wrap them in quotes.
        If not provided, will process all contigs in bam. 
    -o  output folder (default: ${OUTPUT}).
    -s  medaka model for initial SNP calling from mixed reads prior to phasing,
        (default: ${SNPMODEL}).
        ${modeldata[0]}.
        Alternatively a .hdf file from 'medaka train'. 
    -m  medaka model for final variant calling from phased reads,
        (default: ${MODEL}).
        ${modeldata[0]}.
        Alternatively a .hdf file from 'medaka train'. 
    -T  label probability threshold for calling heterozygous SNPs from unphased
        reads. (default: ${THRESHOLD}).
    -t  number of threads with which to create features (default: 1).
    -b  batchsize, controls memory use (default: ${BATCH_SIZE}).
    -d  delete intermediate files. (default: keep)."


while getopts ':hi::f:r:o:m:s:T:t:b:d' option; do
  case "$option" in
    h  ) echo "$usage" >&2; exit;;
    i  ) iflag=true; CALLS2REF=$(follow_link $OPTARG);;
    f  ) fflag=true; REF=$(follow_link $OPTARG);;
    r  ) REGIONS="$OPTARG";;
    o  ) OUTPUT=$OPTARG;;
    m  ) MODEL=$(medaka tools resolve_model --model $OPTARG);;
    s  ) SNPMODEL=$(medaka tools resolve_model --model $OPTARG);;
    T  ) THRESHOLD=$OPTARG;;
    t  ) THREADS=$OPTARG;;
    b  ) BATCH_SIZE=$OPTARG;;
    d  ) DELETE=true;;
    \? ) echo "Invalid option: -${OPTARG}." >&2; exit 1;;
    :  ) echo "Option -$OPTARG requires an argument." >&2; exit 1;;
  esac
done
shift $(($OPTIND - 1))

if ! $iflag; then
  echo "$usage" >&2;
  echo "" >&2;
  echo "-i must be specified." >&2;
  exit 1;
fi

if ! $fflag; then
  echo "$usage" >&2;
  echo "" >&2;
  echo "-f must be specified." >&2;
  exit 1;
fi

run_extract_region_from_bam () {
    local BAMIN=$1
    local BAMOUT=$2
    local REGIONS=$3

    exit_if_file_does_not_exist ${BAMIN} ${BAMIN}.bai
    if [[ ! -e ${BAMOUT} ]]; then
        echo ""
        echo "- Extracting regions $REGIONS from bam ${BAMIN} "
        samtools view -b -h ${BAMIN} -@ ${THREADS} -o ${BAMOUT} ${REGIONS} \
            || (echo "Failed to extract regions from bam." && exit 1)
    else 
        echo "Not extracting regions from bam, ${BAMOUT} exists."
    fi
    run_samtools_index ${BAMOUT}
}

run_medaka_consensus () {
    local BAM=$1
    local PROBS=$2
    local MEDAKAMODEL=$3
    local EXTRAOPTS=$4
    if [ -n "${REGIONS}" ]; then
        local REG_OPT="--regions ${REGIONS}"
    else
        local REG_OPT=""
    fi
    exit_if_file_does_not_exist ${BAM} ${BAM}.bai
    if [[ ! -e ${PROBS} ]]; then
        echo ""
        echo "- Running medaka consensus with ${BAM} --model ${MEDAKAMODEL} ${EXTRAOPTS}"
        medaka consensus ${BAM} ${PROBS} --model ${MEDAKAMODEL} --batch_size ${BATCH_SIZE} ${REG_OPT} --threads ${THREADS} ${EXTRAOPTS} \
            || (echo "Failed to run medaka consensus." && exit 1)
    else 
        echo "Not running medaka consensus, ${PROBS} exists."
    fi
}

run_medaka_snp () {
    local PROBS=$1
    local VCF=$2
    local T=$3
    local EXTRAOPTS=$4
    if [ -n "${REGIONS}" ]; then
        local REG_OPT="--regions ${REGIONS}"
    else
        local REG_OPT=""
    fi
    exit_if_file_does_not_exist ${PROBS} ${REF}
    if [[ ! -e ${VCF} ]]; then
        echo ""
        echo "- Running medaka snp with threshold ${T}"
        medaka snp ${REF} ${PROBS} ${VCF} --threshold ${T} ${REG_OPT} ${EXTRAOPTS} \
            || (echo "Failed to call snps from consensus probabilities." && exit 1)
        echo "VCF written to ${OUTPUT}/${VCF}."
    else
        echo "Using existing output:  ${OUTPUT}/${VCF}."
    fi
}

run_medaka_variant () {
    local PROBS=$1
    local VCF=$2
    local EXTRAOPTS=$4
    if [ -n "${REGIONS}" ]; then
        local REG_OPT="--regions ${REGIONS}"
    else
        local REG_OPT=""
    fi
    exit_if_file_does_not_exist ${PROBS} ${REF}
    if [[ ! -e ${VCF} ]]; then
        echo ""
        echo "- Running medaka variant"
        medaka variant ${REF} ${PROBS} ${VCF} ${REG_OPT} ${EXTRAOPTS} \
            || (echo "Failed to call variants from consensus probabilities." && exit 1)
        echo "VCF written to ${OUTPUT}/${VCF}."
    else
        echo "Using existing output:  ${OUTPUT}/${VCF}."
    fi
}

run_medaka_haploid2diploid () {
    # by default returns a phased vcf
    local VCF1=$1
    local VCF2=$2
    local REF=$3
    local MERGED=$4

    exit_if_file_does_not_exist ${VCF1} ${VCF2} ${REF}
    if [[ ! -e ${MERGED} ]]; then
        echo ""
        echo "- Running medaka haploid2diploid "
        medaka tools haploid2diploid ${VCF1} ${VCF2} ${REF} ${MERGED} \
            || (echo "Failed to run medaka haploid2diploid." && exit 1)
        echo "VCF written to ${OUTPUT}/${MERGED}."
    else
        echo "Using existing output:  ${OUTPUT}/${MERGED}."
    fi
}

run_phase_vcf () {
    local VCFIN=$1 
    local VCFOUT=$2
    exit_if_file_does_not_exist ${VCFIN}
    run_samtools_faidx ${REF}
    if [[ ! -e ${VCFOUT} ]]; then
        echo ""
        echo "- Running whatshap phase for: ${VCFIN} > ${VCFOUT}."
        whatshap phase --reference ${REF} -o ${VCFOUT} ${VCFIN} ${CALLS2REF} ${WHATSHAPOPTS} \
            || (echo "Failed to phase variants in ${VCFIN}." && exit 1)
        echo "Phased VCF written to ${OUTPUT}/${VCFOUT}."
    else
        echo "Using existing output:  ${OUTPUT}/${VCFOUT}."
    fi
}

run_whatshap_tag () {
    local VCFIN=$1
    local BAMOUT=$2
    if [[ ! -e ${BAMOUT} ]]; then
        echo ""
        echo "- Running whatshap tag for: ${VCFIN} > ${BAMOUT}"
        whatshap haplotag -o ${BAMOUT} --reference ${REF} ${VCFIN} ${CALLS2REF} ${WHATSHAPOPTS} \
            || (echo "Failed to partition reads in round 0." && exit 1)
        echo "Tagged reads written to ${OUTPUT}/${BAMOUT}."
    else
        echo "Using existing output:  ${OUTPUT}/${BAMOUT}."
    fi
    run_samtools_index ${BAMOUT}
}

run_bgzip () {
    local FILEIN=$1
    local FILEOUT=$2
    exit_if_file_does_not_exist ${FILEIN}
    if [[ ! -e ${FILEOUT} ]]; then
        echo "Compressing ${FILEIN}."
        bgzip -c ${FILEIN} > ${FILEOUT} \
            || (echo "Failed to compress ${FILEIN}." && exit 1)
        echo "Compressed file written to ${OUTPUT}/${FILEOUT}."
    else
        echo "Using existing output:  ${OUTPUT}/${FILEOUT}."
    fi
    run_tabix ${FILEOUT} 
}

run_tabix () {
    local FILEIN=$1
    local FILEOUT=${1}.tbi
    exit_if_file_does_not_exist ${FILEIN}
    if [[ ! -e ${FILEOUT} ]]; then
        echo "Indexing ${FILEIN}."
        tabix -p vcf ${FILEIN} \
            || (echo "Failed to compress ${FILEIN}." && exit 1)
        echo "Compressed file written to ${OUTPUT}/${FILEOUT}."
    else
        echo "Using existing output:  ${OUTPUT}/${FILEOUT}."
    fi
}

run_samtools_faidx () {
    local FILEIN=$1
    local FILEOUT=${1}.fai
    exit_if_file_does_not_exist ${FILEIN}
    if [[ ! -e ${FILEOUT} ]]; then
        echo "Indexing ${FILEIN}."
        samtools faidx ${FILEIN} \
            || (echo "Failed to index ${FILEIN}." && exit 1)
        echo "Created index ${OUTPUT}/${FILEOUT}."
    else
        echo "Using existing output:  ${OUTPUT}/${FILEOUT}."
    fi
}

run_samtools_index () {
    local BAM=$1
    local INDEX=${BAM}.bai
    exit_if_file_does_not_exist ${BAM}

    if [[ ! -e ${INDEX} ]]; then
        echo "Running samtools index on ${BAM}."
        samtools index -@ ${THREADS} ${BAM}  \
            || (echo "Failed to index bam ${BAM}." && exit 1)
        echo "Bam index in ${OUTPUT}/${INDEX}."
    else
        echo "Using existing output:  ${OUTPUT}/${INDEX}."
    fi
}

exit_if_file_does_not_exist () {
    for FILE in "$@"; do
        if [[ ! -e ${FILE} ]]; then
            echo "Could not find file ${FILE}, exiting." && exit 1
        fi
    done
}

run_haplotyped_pass () {
    # Run a variant calling pass from a haplotagged bam
    local ITER=$1
    local INBAM=$2
    local DECODE_OPTS=$3

    PROBSHAP1=round_${ITER}_hap_1_probs.hdf
    run_medaka_consensus ${INBAM} ${PROBSHAP1} ${MODEL} "${HAP1OPTS}"
    PROBSHAP2=round_${ITER}_hap_2_probs.hdf
    run_medaka_consensus ${INBAM} ${PROBSHAP2} ${MODEL} "${HAP2OPTS}" 

    VCFHAP1=round_${ITER}_hap_1.vcf
    VCFHAP2=round_${ITER}_hap_2.vcf

    if [ "$DECODE_OPTS" == "snp" ]; then
        run_medaka_snp ${PROBSHAP1} ${VCFHAP1} ${THRESHOLD}
        run_medaka_snp ${PROBSHAP2} ${VCFHAP2} ${THRESHOLD}
    else
        run_medaka_variant ${PROBSHAP1} ${VCFHAP1}
        run_medaka_variant ${PROBSHAP2} ${VCFHAP2}
    fi


    VCFPHASED=round_${ITER}_phased.vcf
    run_medaka_haploid2diploid ${VCFHAP1} ${VCFHAP2} ${REF} ${VCFPHASED}
    VCFPHASEDGZ=${VCFPHASED}.gz 
    run_bgzip ${VCFPHASED} ${VCFPHASEDGZ}
}


###
# Set-up
echo "Checking program versions"
medaka_version_report || exit 1

if [[ ! -e ${OUTPUT} ]]; then
  mkdir -p ${OUTPUT}
else
  echo "Warning: Output ${OUTPUT} already exists, may use old results."
fi

cd ${OUTPUT}

# check input bam, bam index and ref exist
exit_if_file_does_not_exist ${CALLS2REF} ${CALLS2REF}.bai ${REF}

# if regions have been provided, extract that region from the input bam
# (whatshap currently does not have a region string option). 

if [ -n "${REGIONS}" ]; then
    CALLS2REF_EXTRACTED=$(basename ${CALLS2REF})
    run_extract_region_from_bam ${CALLS2REF} ${CALLS2REF_EXTRACTED} ${REGIONS}
    CALLS2REF=${CALLS2REF_EXTRACTED}
fi


###
# First pass to haplotag reads
echo ""
echo "+ Running initial pass to haplotag reads."
ROUND=0

CONSENSUSPROBS=round_${ROUND}_hap_mixed_probs.hdf
run_medaka_consensus ${CALLS2REF} ${CONSENSUSPROBS} ${SNPMODEL}

UNPHASEDVCF=round_${ROUND}_hap_mixed_thresh_${THRESHOLD}_unphased.vcf
run_medaka_snp ${CONSENSUSPROBS} ${UNPHASEDVCF} ${THRESHOLD}

PHASEDVCF=round_${ROUND}_hap_mixed_thresh_${THRESHOLD}_phased.vcf
run_phase_vcf ${UNPHASEDVCF} ${PHASEDVCF} 

PHASEDVCFGZ=${PHASEDVCF}.gz
run_bgzip ${PHASEDVCF} ${PHASEDVCFGZ}

PHASEDBAM=round_${ROUND}_hap_mixed_thresh_${THRESHOLD}_phased.bam
run_whatshap_tag ${PHASEDVCFGZ} ${PHASEDBAM}


###
# Second pass to call haplotypes and merge to form phased diploid vcf
echo ""
echo "+ Running final pass to produce variant calls."
ROUND=1
DECODING_OPTS="variant"
run_haplotyped_pass ${ROUND} ${PHASEDBAM} ${DECODING_OPTS}

###
# Cleanup
if ${DELETE}; then
  files=$(ls *.hdf *.bam *.bai *.gz *.tbi)
  echo ""
  echo "Deleting intermediate files:"
  echo "${files}"
  rm ${files}
fi
echo ""
echo "All done." 
echo "Final unphased VCF written to ${OUTPUT}/round_${ROUND}.vcf"
echo "Final phased VCF written to ${OUTPUT}/round_${ROUND}_phased.vcf"
